package Model.AnimalInfo.Species;

public enum Bird {
    BUDGERIGAR, COCKATIEL, CANARY, LOVEBIRD, PARROTLET, CONURE, AFRICAN_GREY_PARROT, COCKATOO, FINCH, AMAZON_PARROT,
    MACAW, QUAKER_PARROT, SENEGAL_PARROT, CAIQUE, PARAKEET, DOVE, DIAMOND_DOVE, PIONUS, BOURKES_PARAKEET,
    ECLECTUS, OTHER
}
