package Model.AnimalInfo.Species;

public enum Duck {
    CALL, PEKIN, KHAKI_CAMPBELL, INDIAN_RUNNER, WELSH_HARLEQUIN, CAYUGA, MUSCOVY, MALLARD, SWEDISH_BLUE, ROUEN,
    ANCONA, SILVER_APPLEYARD, BUFF_ORPINGTON, BLUE_SWEDISH, MAGPIE, SAXONY, CRESTED, WHITE_CRESTED, BLACK_EAST_INDIAN,
    AYLESBURY, OTHER
}
