package Model.AnimalInfo.Species;

public enum Goose {
    CHINESE, EMBDEN, TOULOUSE, AFRICAN, PILGRIM, SEBASTOPOL, AMERICAN_BUFF, ROMAN, EGYPTIAN, POMERANIAN, SHETLAND,
    CANADA, BUFF, COTTON_PATCH, TUFTED_ROMAN, STEINBACHER, WEST_OF_ENGLAND, BRECON_BUFF, GREYLAG,
    EMDEN_WHITE, SNOW, OTHER;
}
